# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Article Images', 'verbose_name_plural': 'Article Images'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='articleimage',
            table='Article Images',
        ),
    ]
