# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170407_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimage',
            old_name='optional_image',
            new_name='artile',
        ),
        migrations.RenameField(
            model_name='articleimage',
            old_name='article_name',
            new_name='image_name',
        ),
    ]
