# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170407_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'article_category',
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Category',
            },
        ),
    ]
