# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170407_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(default='None', upload_to='article_images'),
        ),
    ]
